name: Melodic CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: docker setup and build
        run: docker build . -t mesh_nav/melodic -f ci/Dockerfile-melodic
